### ISSUE TITLE
AddEnvironmentCleanupHook not supported in Node v10.1.0

### ISSUE THREAD

**Issue by CharlieHess** [atom/keyboard-layout#55]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Are we sure that `AddEnvironmentCleanupHook` is included in all versions of Node 10? I tried a rebuild using Node 10.1.0 and got:

```
> keyboard-layout@2.0.16 install /Users/charlie/dnd-observer
> node-gyp rebuild

  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager.o
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-mac.o
../src/keyboard-layout-manager-mac.mm:47:9: error: no member named 'AddEnvironmentCleanupHook' in
      namespace 'node'
  node::AddEnvironmentCleanupHook(
  ~~~~~~^
../src/keyboard-layout-manager-mac.mm:56:9: error: no member named 'RemoveEnvironmentCleanupHook'
      in namespace 'node'
  node::RemoveEnvironmentCleanupHook(
  ~~~~~~^
2 errors generated.
```

Upgrading to Node LTS fixed the issue.

**Comment by lkashef** [comment]
Hey @CharlieHess, I am glad your problem has been resolved.
